# Generated by Django 5.1.6 on 2025-03-01 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=60)),
                ('country_image', models.ImageField(upload_to='country_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnivDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo/')),
                ('nominal_duration', models.CharField(max_length=40)),
                ('awards', models.TextField()),
                ('tuition_fee', models.CharField(max_length=60)),
                ('application_fee', models.CharField(max_length=60)),
                ('registration_fee', models.CharField(max_length=60)),
                ('tuition_desc', models.TextField()),
                ('entry_qualication', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image/')),
                ('home_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.home')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('date_of_foundation', models.DateField(auto_now=True)),
                ('programs', models.TextField()),
                ('languages', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univ_country', to='course_app.country')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.univdescription')),
                ('education', models.ManyToManyField(to='course_app.education')),
                ('specialities', models.ManyToManyField(to='course_app.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image/')),
                ('university_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.university')),
            ],
        ),
    ]
