# Generated by Django 5.1.6 on 2025-03-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_cambrigeexam_consultation_exam_studentreview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='exam',
        ),
    ]
