# Generated by Django 5.1.6 on 2025-03-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_remove_home_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.univdescription'),
        ),
    ]
