# Generated by Django 5.1.6 on 2025-03-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_university_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univdescription',
            name='cost',
            field=models.TextField(blank=True, null=True),
        ),
    ]
