# Generated by Django 5.1.6 on 2025-03-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_alter_universityimage_university_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.AddField(
            model_name='univdescription',
            name='university',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='course_app.university'),
            preserve_default=False,
        ),
    ]
