# Generated by Django 5.1.6 on 2025-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_remove_university_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cambrigeexam',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cambrigeexam',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cambrigeexam',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cambrigeexam',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studyabroadprogram',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studyabroadprogram',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studyabroadprogram',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studyabroadprogram',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='speciality_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='speciality_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='location_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='location_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
