# Generated by Django 5.1.6 on 2025-03-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_remove_university_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='created_at',
        ),
    ]
